server:
  port: 8081
spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  application:
    name: "AUTHENTICATION"
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;serverName=PC-324;databaseName=way;encrypt=true;trustServerCertificate=true;
    username: sa
    password: asd123!@#
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full


#logging:
#  level:
#    root: info

jwt:
  secretKey: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwMDYzODUzNywiaWF0IjoxNzAwNjM4NTM3fQ.cakxNusKVbUYfXIO_ldis-uQtQMxRO58Tktr31X6O_I
  expirationMinutes: 60
  expirationCaptchaMinutes: 1

eureka:
  baseServerUrl: localhost
  client:
    service-url:
      defaultZone: http://${eureka.baseServerUrl}:8080/eureka

PageRequest:
  page: 0
  size: 10

springdoc:
  swagger-ui:
    server-url: http://localhost:8083
    path: index.html
    enabled: true
    config-url: /authenticationSwagger/v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /authenticationSwagger/v3/api-docs

authentication:
  paths-to-bypass: /login/**, /authentication/getUserId/**, /authentication/getUser/**, /authentication/checkValidationToken/**,/v3/api-docs/**, /swagger-ui/**, /swagger-ui.html , /authentication/captcha/generate
  captcha-length : 4
  captcha-width : 160
  captcha-height : 50
